// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "content-backend",
    "version": "1"
  },
  "paths": {
    "/users": {
      "post": {
        "summary": "createUser",
        "description": "",
        "tags": [
          "Users"
        ],
        "operationId": "createUser.post.users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/IUserBodyType"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/IUser"
            }
          },
          "422": {
            "description": "Unprocessable",
            "schema": {
              "$ref": "#/definitions/IError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Date": {
      "title": "Date"
    },
    "IError": {
      "properties": {
        "status": {
          "title": "IError.status",
          "type": "number"
        },
        "message": {
          "title": "IError.message",
          "type": "string"
        }
      },
      "required": [
        "status"
      ],
      "additionalProperties": false,
      "title": "IError",
      "type": "object"
    },
    "IResponseHeaders": {
      "additionalProperties": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "number"
          },
          {
            "type": "string"
          }
        ]
      },
      "title": "IResponseHeaders",
      "type": "object"
    },
    "IFindOptions": {
      "properties": {
        "page": {
          "title": "IFindOptions.page",
          "type": "number"
        },
        "pageSize": {
          "title": "IFindOptions.pageSize",
          "type": "number"
        },
        "sort": {
          "items": {
            "title": "IFindOptions.sort.[]",
            "type": "string"
          },
          "title": "IFindOptions.sort",
          "type": "array"
        }
      },
      "required": [
        "page",
        "pageSize",
        "sort"
      ],
      "additionalProperties": false,
      "title": "IFindOptions",
      "type": "object"
    }
  },
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "basePath": "/dev"
};